

stty -F /dev/my_serial_port <baud_rate> cs8 cread clocal
As always, read the manpage before applying the above.  cread allows you to receive data. You may want to omit clocal if you are using flow control. If you aren't sure what the above settings are, ask, and I can write up a more complete answer.

* Intro
v0.1

This is the firmware for an EggBot-style SphereBot.
The firmware directly interprets GCode send over the serial port.

Detailed build instructions can be found on [[http://www.instructables.com/id/3D-Printed-Arduino-Controlled-EggbotSpherepot/][instructables]].

* Usage

** Installation
This sketch uses the following non-standard libraries (install them in the Arduino library directory):
[[http://www.arduino.cc/playground/ComponentLib/Servo][SoftwareServo]]
[[http://www.arduino.cc/playground/Code/Timer1][TimerOne]]

Install the libraries
#+BEGIN_SRC sh
unzip TimerOne* -d TimerOne
sudo mv TimerOne /usr/share/arduino/libraries/
#+END_SRC

Remember to set the MS1-MS3 pins on the stepstick to high in order to enable micro stepping - not low as the =wireScheme= shows

I'm using the SM42HT47-1684A stepper motors with 1.8°/step, eg set the following in =SphereBot.ino=:
XAXIS_STEP_PER_REVOLUTION = 200; //  360° / 1.8 °/step = 200


** GCode commands

The scaling and speed does not work completely.
For the files en the /gcode/ folder, add this:
M402 S3.5 (zoom)
and set the fill speed to F10000.00


M01 Change pen

G90	Absolut modus
G91	Icremental modus:

M300S0	Servo 0 degree
M300S90	Servo 90 degree


M18	Stepper off

G0X0Y40	Rapid movement (pen 0mm, rotation 40mm)
G1X40Y0 Slower movement (pen 40mm, rotation 0mm)
G1Y10F660 Movement with feed 660mm/s (rotation 10mm)

;	Comment
( .. )	Comment

* Copyright
Copyright 2011 by Eberhard Rensch <http://pleasantsoftware.com/developer/3d>
Released under the GPLv3

Part of this code is based on/inspired by the Helium Frog Delta Robot Firmware
by Martin Price <http://www.HeliumFrog.com>
